
use role sysadmin;

-- Helper Stored Procedures
--
-- CALL TPCDI_STG.BASE.DROP_ALL_DT();
-- CALL TPCDI_ODS.BASE.DROP_ALL_DT();
-- CALL TPCDI_WH.BASE.DROP_ALL_DT();

USE WAREHOUSE ETL_WH;

USE SCHEMA TPCDI_WH.BASE;
SHOW DYNAMIC TABLES;

USE SCHEMA TPCDI_STG.BASE;
SELECT SCALE, BATCH, STEP, STMT FROM LOAD_PLAN ORDER BY SCALE, BATCH, STEP;

CALL TPCDI_STG.BASE.TRUNCATE_STAGE();

-- Load Scale 5, Scale 10 from Internal Stage TPCDI_FILES
CALL LOAD_ALL('5','1');
CALL LOAD_ALL('10','1');

-- Load Scale 100 from External Stage TPCDI_EXTERNAL
CALL LOAD_ALL('100','1');

-- More load batches
CALL LOAD_ALL('5','2');
CALL LOAD_ALL('10','2');
CALL LOAD_ALL('100','2');

CALL LOAD_ALL('5','3');
CALL LOAD_ALL('10','3');
CALL LOAD_ALL('100','3');

CALL LOAD_ALL('5','4');
CALL LOAD_ALL('10','4');
CALL LOAD_ALL('100','4');

CALL LOAD_ALL('5','5');
CALL LOAD_ALL('10','5');
CALL LOAD_ALL('100','5');