timer_trigger = "30"
hostnamesfsuffex = ".snowflakecomputing.com"
sfuser = "client_redirect_test_user"
sfpassword = "_hnJAXJHqhN*!78K9pjUfTH-Fn_@Z*"
sfdb = "SNOWFLAKE_HA_MONITOR"
sfschema = "PUBLIC"
portnumber = "443"
failovergroup = "universe1_fog"
sfclientredirectconnname = "universe1"
sfaccountpri = "az_demo28.east-us-2.azure"
sfaccountsec = "va_demo06.us-east-1"
sfhamonitor = "{'test_wh_1': 'use warehouse snowflake_ha_monitor_1_wh;', 'test_query_1': 'call snowflake_ha_monitor_sp();', 'test_wh_2': 'use warehouse snowflake_ha_monitor_2_wh;', 'test_query_2': 'call snowflake_ha_monitor_sp();'}"
triesnum = "2"
sleeptime = "5"
enablefallback = "yes"
sfaccountlocatorprimary = "AZ_DEMO28"
sfaccountlocatorsecondary = "VA_DEMO06"
sfglobalaccountname = "sfsenorthamerica-universe1"
cfprotocol = "TCP"