timer_trigger = "30"
hostnamesfsuffex = ".snowflakecomputing.com"
sfuser = "user name with accountadmin role"
sfpassword = "password"
sfdb = "SNOWFLAKE_HA_MONITOR"
sfschema = "PUBLIC"
portnumber = "443"
failovergroup = "failover group name from your previous lab"
sfclientredirectconnname = "client redirect connection name from your previous lab"
sfaccountpri = "the source account name until .snowflakecomputing.com please do not include .snowflakecomputing.com here"
sfaccountsec = "the target account name until .snowflakecomputing.com please do not include .snowflakecomputing.com here"
sfhamonitor = "{'test_wh_1': 'use warehouse snowflake_ha_monitor_1_wh;', 'test_query_1': 'call snowflake_ha_monitor_sp();', 'test_wh_2': 'use warehouse snowflake_ha_monitor_2_wh;', 'test_query_2': 'call snowflake_ha_monitor_sp();'}"
triesnum = "2"
sleeptime = "5"
enablefallback = "yes"
sfaccountlocatorprimary = "use select current_account(); to get the account locator in the source account"
sfaccountlocatorsecondary = "use select current_account(); to the account locator in the source account"
sfglobalaccountname = "<your org name>-<your client redirect connection name>"
cfprotocol = "TCP"
